# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addAluno.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddAlunoWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 405)
        MainWindow.setStyleSheet("background-color: #EDFDFF;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(230, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputAluno = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAluno.setGeometry(QtCore.QRect(220, 140, 241, 25))
        self.inputAluno.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"}")
        self.inputAluno.setObjectName("inputAluno")
        self.btnAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdicionar.setGeometry(QtCore.QRect(180, 230, 121, 41))
        self.btnAdicionar.setStyleSheet("QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")
        self.btnAdicionar.setObjectName("btnAdicionar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(330, 230, 121, 41))
        self.btnCancelar.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adicionar Aluno"))
        self.label_1.setText(_translate("MainWindow", "Adicionar Aluno"))
        self.label_2.setText(_translate("MainWindow", "Aluno:"))
        self.btnAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
