# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProfessor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddProfessorWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 335)
        MainWindow.setStyleSheet("background-color: #EDFDFF;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputProfessor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputProfessor.setGeometry(QtCore.QRect(180, 100, 241, 25))
        self.inputProfessor.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"}")
        self.inputProfessor.setObjectName("inputProfessor")
        self.comboBoxDisciplina = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDisciplina.setGeometry(QtCore.QRect(180, 140, 241, 25))
        self.comboBoxDisciplina.setObjectName("comboBoxDisciplina")
        self.comboBoxDisciplina.setStyleSheet("QComboBox {"
        "       background-color: #EDFDFF"
        "}"
        "QComboBox::item:selected {"
        "       color: rgb(53, 62, 64)"
        "}"
        )
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(280, 210, 121, 41))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdicionar.setGeometry(QtCore.QRect(130, 210, 121, 41))
        self.btnAdicionar.setObjectName("btnAdicionar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnCancelar.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnAdicionar.setStyleSheet("QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid rgb(53, 62, 64);\n"
"    border-radius: 5px;\n"
"    color: rgb(53, 62, 64);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")

        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adicionar Professor"))
        self.label.setText(_translate("MainWindow", "Professor:"))
        self.label_2.setText(_translate("MainWindow", "Disciplina:"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.btnAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.label_3.setText(_translate("MainWindow", "Adicionar Professor"))
