# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bimestre.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class ConfirmarWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 316)
        MainWindow.setStyleSheet("background-color: #EDFDFF;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 611, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnSim = QtWidgets.QPushButton(self.centralwidget)
        self.btnSim.setGeometry(QtCore.QRect(140, 190, 141, 51))
        self.btnSim.setStyleSheet("QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid #353e40;\n"
"   border-radius: 5px;\n"
"   color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")
        self.btnSim.setObjectName("btnSim")
        self.btnNao = QtWidgets.QPushButton(self.centralwidget)
        self.btnNao.setGeometry(QtCore.QRect(340, 190, 141, 51))
        self.btnNao.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"    border: 1px solid #353e40;\n"
"   border-radius: 5px;\n"
"   color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnNao.setObjectName("btnNao")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bimestre"))
        self.label.setText(_translate("MainWindow", "Você deseja avançar para o proximo bimestre?"))
        self.btnSim.setText(_translate("MainWindow", "Sim"))
        self.btnNao.setText(_translate("MainWindow", "Não"))
