# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editarProfessor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EditProfessorWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 555)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #EDFDFF;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #353e40;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #353e40;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid #353e40;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 230, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 186, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.professorNome = QtWidgets.QLineEdit(self.centralwidget)
        self.professorNome.setGeometry(QtCore.QRect(280, 140, 321, 31))
        self.professorNome.setObjectName("professorNome")
        self.professorTelefone = QtWidgets.QLineEdit(self.centralwidget)
        self.professorTelefone.setGeometry(QtCore.QRect(280, 220, 321, 31))
        self.professorTelefone.setObjectName("professorTelefone")
        self.professorTelefone.setInputMask('(00) 00000-0000')
        self.btnEditar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditar.setGeometry(QtCore.QRect(270, 350, 131, 61))
        self.btnEditar.setObjectName("btnEditar")
        self.professorEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.professorEmail.setGeometry(QtCore.QRect(280, 180, 321, 31))
        self.professorEmail.setObjectName("professorEmail")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(440, 350, 131, 61))
        self.btnCancelar.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editar Professor"))
        self.label_5.setText(_translate("MainWindow", "Editar Professor"))
        self.label_4.setText(_translate("MainWindow", "Telefone:"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.btnEditar.setText(_translate("MainWindow", "Editar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.label.setText(_translate("MainWindow", "Nome:"))
