# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class NotasWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 487)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #EDFDFF;\n"
"}\n"
"\n"
"QDoubleSpinBox {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid #353e40;\n"
"   border-radius: 5px;\n"
"   color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 320, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.inputP1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputP1.setGeometry(QtCore.QRect(220, 70, 81, 41))
        self.inputP1.setMaximum(10.0)
        self.inputP1.setObjectName("inputP1")
        self.inputR1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputR1.setGeometry(QtCore.QRect(220, 120, 81, 41))
        self.inputR1.setMaximum(10.0)
        self.inputR1.setObjectName("inputR1")
        self.inputP2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputP2.setGeometry(QtCore.QRect(220, 170, 81, 41))
        self.inputP2.setMaximum(10.0)
        self.inputP2.setObjectName("inputP2")
        self.inputR2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputR2.setGeometry(QtCore.QRect(220, 220, 81, 41))
        self.inputR2.setMaximum(10.0)
        self.inputR2.setObjectName("inputR2")
        self.inputP3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputP3.setGeometry(QtCore.QRect(220, 270, 81, 41))
        self.inputP3.setMaximum(10.0)
        self.inputP3.setObjectName("inputP3")
        self.inputR3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.inputR3.setGeometry(QtCore.QRect(220, 320, 81, 41))
        self.inputR3.setMaximum(10.0)
        self.inputR3.setObjectName("inputR3")
        self.btnAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAplicar.setGeometry(QtCore.QRect(30, 400, 131, 61))
        self.btnAplicar.setObjectName("btnAplicar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notas"))
        self.label.setText(_translate("MainWindow", "Prova 1:"))
        self.label_2.setText(_translate("MainWindow", "NOTAS DE:"))
        self.label_3.setText(_translate("MainWindow", "Rec 1:"))
        self.label_4.setText(_translate("MainWindow", "Prova 2:"))
        self.label_5.setText(_translate("MainWindow", "Rec 2:"))
        self.label_6.setText(_translate("MainWindow", "Rec 3:"))
        self.label_7.setText(_translate("MainWindow", "Prova 3:"))
        self.btnAplicar.setText(_translate("MainWindow", "Aplicar"))
