# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class NotasWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 487)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #d3f9ff;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"       border-radius: 5px;\n"
"       color: #353e40;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid #353e40;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.inputP1 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputP1.setGeometry(QtCore.QRect(210, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputP1.setFont(font)
        self.inputP1.setText("")
        self.inputP1.setObjectName("inputP1")
        self.inputR1 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputR1.setGeometry(QtCore.QRect(210, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputR1.setFont(font)
        self.inputR1.setText("")
        self.inputR1.setObjectName("inputR1")
        self.inputP2 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputP2.setGeometry(QtCore.QRect(210, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputP2.setFont(font)
        self.inputP2.setText("")
        self.inputP2.setObjectName("inputP2")
        self.inputR2 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputR2.setGeometry(QtCore.QRect(210, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputR2.setFont(font)
        self.inputR2.setText("")
        self.inputR2.setObjectName("inputR2")
        self.inputP3 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputP3.setGeometry(QtCore.QRect(210, 300, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputP3.setFont(font)
        self.inputP3.setText("")
        self.inputP3.setObjectName("inputP3")
        self.inputR3 = QtWidgets.QLineEdit(self.centralwidget)
        self.inputR3.setGeometry(QtCore.QRect(210, 360, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputR3.setFont(font)
        self.inputR3.setText("")
        self.inputR3.setObjectName("inputR3")
        self.btnAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAplicar.setGeometry(QtCore.QRect(30, 430, 131, 41))
        self.btnAplicar.setObjectName("btnAplicar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notas"))
        self.label.setText(_translate("MainWindow", "prova 1:"))
        self.label_2.setText(_translate("MainWindow", "NOTAS DE:"))
        self.label_3.setText(_translate("MainWindow", "Rec 1:"))
        self.label_4.setText(_translate("MainWindow", "prova 2:"))
        self.label_5.setText(_translate("MainWindow", "Rec 2:"))
        self.label_6.setText(_translate("MainWindow", "Rec 3:"))
        self.label_7.setText(_translate("MainWindow", "prova 3:"))
        self.btnAplicar.setText(_translate("MainWindow", "Aplicar"))
