# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel-adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AdmWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1414, 816)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 0, 1371, 821))
        self.frame.setStyleSheet("background-color: #EDFDFF;\n"
"border: none;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 10, 1241, 791))
        self.stackedWidget.setStyleSheet("QLabel {\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #353e40;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #353e40;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: #e6e6e6;\n"
"    \n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #8ED498;\n"
"    border: 1px solid #353e40;\n"
"    border-radius: 5px;\n"
"    color: #353e40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #85C78F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #74AD7D;\n"
"}\n"
"\n"
"QDateTimeEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 5px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageAddProfessor = QtWidgets.QWidget()
        self.pageAddProfessor.setObjectName("pageAddProfessor")
        self.label = QtWidgets.QLabel(self.pageAddProfessor)
        self.label.setGeometry(QtCore.QRect(480, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_8.setGeometry(QtCore.QRect(390, 226, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_9.setGeometry(QtCore.QRect(370, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.active_button = False
                
        self.cpfProfessor = QtWidgets.QLineEdit(self.pageAddProfessor)
        self.cpfProfessor.setGeometry(QtCore.QRect(430, 220, 321, 31))
        self.cpfProfessor.setObjectName("cpfProfessor")

        self.label_10 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_10.setGeometry(QtCore.QRect(260, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.nomeProfessor = QtWidgets.QLineEdit(self.pageAddProfessor)
        self.nomeProfessor.setGeometry(QtCore.QRect(430, 140, 321, 31))
        self.nomeProfessor.setObjectName("nomeProfessor")
        self.label_11 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_11.setGeometry(QtCore.QRect(370, 260, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.emailProfessor = QtWidgets.QLineEdit(self.pageAddProfessor)
        self.emailProfessor.setGeometry(QtCore.QRect(430, 260, 321, 31))
        self.emailProfessor.setObjectName("emailProfessor")
        self.btnAdicionarProfessor = QtWidgets.QPushButton(self.pageAddProfessor)
        self.btnAdicionarProfessor.setGeometry(QtCore.QRect(510, 400, 131, 61))
        self.btnAdicionarProfessor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnAdicionarProfessor.setStyleSheet("")
        self.btnAdicionarProfessor.setObjectName("btnAdicionarProfessor")
        self.dataProfessor = QtWidgets.QDateTimeEdit(self.pageAddProfessor)
        self.dataProfessor.setGeometry(QtCore.QRect(430, 180, 321, 31))
        self.dataProfessor.setDate(QtCore.QDate(2000, 1, 1))
        self.dataProfessor.setTime(QtCore.QTime(0, 0, 0))
        self.dataProfessor.setCalendarPopup(False)
        self.dataProfessor.setObjectName("dataProfessor")
        self.dataProfessor.setMinimumDate(QtCore.QDate(1911, 1, 1))
        self.label_17 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_17.setGeometry(QtCore.QRect(370, 340, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.professorSexo = QtWidgets.QComboBox(self.pageAddProfessor)
        self.professorSexo.setGeometry(QtCore.QRect(430, 340, 321, 31))
        self.professorSexo.setObjectName("professorSexo")
        self.professorSexo.addItem("")
        self.professorSexo.addItem("")
        self.professorSexo.addItem("")
        self.telefoneProfessor = QtWidgets.QLineEdit(self.pageAddProfessor)
        self.telefoneProfessor.setGeometry(QtCore.QRect(430, 300, 321, 31))
        self.telefoneProfessor.setObjectName("telefoneProfessor")
        self.label_20 = QtWidgets.QLabel(self.pageAddProfessor)
        self.label_20.setGeometry(QtCore.QRect(350, 300, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.stackedWidget.addWidget(self.pageAddProfessor)
        self.pageAddAluno = QtWidgets.QWidget()
        self.pageAddAluno.setObjectName("pageAddAluno")
        self.label_2 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_2.setGeometry(QtCore.QRect(510, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_3.setGeometry(QtCore.QRect(370, 140, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_4.setGeometry(QtCore.QRect(260, 170, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_5.setGeometry(QtCore.QRect(390, 216, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_7.setGeometry(QtCore.QRect(320, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.alunoNome = QtWidgets.QLineEdit(self.pageAddAluno)
        self.alunoNome.setGeometry(QtCore.QRect(430, 130, 321, 31))
        self.alunoNome.setObjectName("alunoNome")
        self.cpfAluno = QtWidgets.QLineEdit(self.pageAddAluno)
        self.cpfAluno.setGeometry(QtCore.QRect(430, 210, 321, 31))
        self.cpfAluno.setStyleSheet("")
        self.cpfAluno.setObjectName("cpfAluno")
        self.responsavelAluno = QtWidgets.QLineEdit(self.pageAddAluno)
        self.responsavelAluno.setGeometry(QtCore.QRect(430, 250, 321, 31))
        self.responsavelAluno.setStyleSheet("")
        self.responsavelAluno.setObjectName("responsavelAluno")
        self.btnAdicionarAluno = QtWidgets.QPushButton(self.pageAddAluno)
        self.btnAdicionarAluno.setGeometry(QtCore.QRect(510, 440, 131, 61))
        self.btnAdicionarAluno.setObjectName("btnAdicionarAluno")
        self.dataAluno = QtWidgets.QDateTimeEdit(self.pageAddAluno)
        self.dataAluno.setGeometry(QtCore.QRect(430, 170, 321, 31))
        self.dataAluno.setObjectName("dataAluno")
        self.dataAluno.setMinimumDate(QtCore.QDate(1911, 1, 1))
        self.label_6 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_6.setGeometry(QtCore.QRect(370, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.emailAluno = QtWidgets.QLineEdit(self.pageAddAluno)
        self.emailAluno.setGeometry(QtCore.QRect(430, 290, 321, 31))
        self.emailAluno.setObjectName("emailAluno")
        self.alunoSexo = QtWidgets.QComboBox(self.pageAddAluno)
        self.alunoSexo.setGeometry(QtCore.QRect(430, 370, 321, 31))
        self.alunoSexo.setObjectName("alunoSexo")
        self.alunoSexo.addItem("")
        self.alunoSexo.addItem("")
        self.alunoSexo.addItem("")
        self.label_18 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_18.setGeometry(QtCore.QRect(380, 370, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.pageAddAluno)
        self.label_19.setGeometry(QtCore.QRect(350, 330, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.telefoneAluno = QtWidgets.QLineEdit(self.pageAddAluno)
        self.telefoneAluno.setGeometry(QtCore.QRect(430, 330, 321, 31))
        self.telefoneAluno.setObjectName("telefoneAluno")
        self.stackedWidget.addWidget(self.pageAddAluno)
        self.pageVerAlunos = QtWidgets.QWidget()
        self.pageVerAlunos.setObjectName("pageVerAlunos")
        self.label_13 = QtWidgets.QLabel(self.pageVerAlunos)
        self.label_13.setGeometry(QtCore.QRect(320, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.inputBuscarAlunos = QtWidgets.QLineEdit(self.pageVerAlunos)
        self.inputBuscarAlunos.setGeometry(QtCore.QRect(390, 100, 331, 31))
        self.inputBuscarAlunos.setObjectName("inputBuscarAlunos")
        self.btnBuscarAlunos = QtWidgets.QPushButton(self.pageVerAlunos)
        self.btnBuscarAlunos.setGeometry(QtCore.QRect(730, 100, 121, 31))
        self.btnBuscarAlunos.setObjectName("btnBuscarAlunos")
        self.tabela_aluno = QtWidgets.QTableWidget(self.pageVerAlunos)
        self.tabela_aluno.setGeometry(QtCore.QRect(50, 210, 1021, 561))
        self.tabela_aluno.setStyleSheet("background-color: white;\n"
"border: 1px solid #9FBBBF;\n"
"")
        self.tabela_aluno.setDragDropOverwriteMode(True)
        self.tabela_aluno.setCornerButtonEnabled(False)
        self.tabela_aluno.setObjectName("tabela_aluno")
        self.tabela_aluno.setColumnCount(6)
        self.tabela_aluno.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_aluno.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_aluno.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_aluno.setItem(0, 2, item)
        self.tabela_aluno.horizontalHeader().setDefaultSectionSize(165)
        self.tabela_aluno.verticalHeader().setDefaultSectionSize(50)
        self.btnEditarAlunos = QtWidgets.QPushButton(self.pageVerAlunos)
        self.btnEditarAlunos.setGeometry(QtCore.QRect(1090, 210, 121, 51))
        self.btnEditarAlunos.setStyleSheet("QPushButton {\n"
"    background-color: #d3f9ff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BEE0E6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9FBBBF;\n"
"}")
        self.btnEditarAlunos.setObjectName("btnEditarAlunos")
        self.btnExcluirAlunos = QtWidgets.QPushButton(self.pageVerAlunos)
        self.btnExcluirAlunos.setGeometry(QtCore.QRect(1090, 360, 121, 51))
        self.btnExcluirAlunos.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnExcluirAlunos.setObjectName("btnExcluirAlunos")
        self.btnVerNotas = QtWidgets.QPushButton(self.pageVerAlunos)
        self.btnVerNotas.setObjectName("btnVerNotas")
        self.btnVerNotas.setText('Ver Notas')
        self.btnVerNotas.setGeometry(QtCore.QRect(1090, 280, 121, 51))
        self.btnVerNotas.setStyleSheet("QPushButton {\n"
"    background-color: #d3f9ff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BEE0E6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9FBBBF;\n"
"}")
        self.label_14 = QtWidgets.QLabel(self.pageVerAlunos)
        self.label_14.setGeometry(QtCore.QRect(480, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.pageVerAlunos)
        self.pageVerProfessores = QtWidgets.QWidget()
        self.pageVerProfessores.setObjectName("pageVerProfessores")
        self.label_15 = QtWidgets.QLabel(self.pageVerProfessores)
        self.label_15.setGeometry(QtCore.QRect(480, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.inputBuscarProfessores = QtWidgets.QLineEdit(self.pageVerProfessores)
        self.inputBuscarProfessores.setGeometry(QtCore.QRect(390, 100, 331, 31))
        self.inputBuscarProfessores.setObjectName("inputBuscarProfessores")
        self.label_16 = QtWidgets.QLabel(self.pageVerProfessores)
        self.label_16.setGeometry(QtCore.QRect(320, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.btnBuscarProfessor = QtWidgets.QPushButton(self.pageVerProfessores)
        self.btnBuscarProfessor.setGeometry(QtCore.QRect(730, 100, 121, 31))
        self.btnBuscarProfessor.setObjectName("btnBuscarProfessor")
        self.btnEditarProfessor = QtWidgets.QPushButton(self.pageVerProfessores)
        self.btnEditarProfessor.setGeometry(QtCore.QRect(1090, 210, 121, 51))
        self.btnEditarProfessor.setStyleSheet("QPushButton {\n"
"    background-color: #d3f9ff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BEE0E6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9FBBBF;\n"
"}")
        self.btnEditarProfessor.setObjectName("btnEditarProfessor")
        self.btnExcluirProfessor = QtWidgets.QPushButton(self.pageVerProfessores)
        self.btnExcluirProfessor.setGeometry(QtCore.QRect(1090, 280, 121, 51))
        self.btnExcluirProfessor.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #BF8177;\n"
"}")
        self.btnExcluirProfessor.setObjectName("btnExcluirProfessor")
        self.tabela_professor = QtWidgets.QTableWidget(self.pageVerProfessores)
        self.tabela_professor.setGeometry(QtCore.QRect(50, 210, 1021, 561))
        self.tabela_professor.setStyleSheet("background-color: white;\n"
"border: 1px solid #9FBBBF;")
        self.tabela_professor.setObjectName("tabela_professor")
        self.tabela_professor.setColumnCount(5)
        self.tabela_professor.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_professor.setHorizontalHeaderItem(4, item)
        self.tabela_professor.horizontalHeader().setDefaultSectionSize(200)
        self.tabela_professor.verticalHeader().setDefaultSectionSize(50)
        self.stackedWidget.addWidget(self.pageVerProfessores)
        self.pageTurmas = QtWidgets.QWidget()
        self.pageTurmas.setObjectName("pageTurmas")
        self.label_21 = QtWidgets.QLabel(self.pageTurmas)
        self.label_21.setGeometry(QtCore.QRect(560, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.listaTurmas = QtWidgets.QListWidget(self.pageTurmas)
        self.listaTurmas.setGeometry(QtCore.QRect(90, 120, 1091, 631))
        self.listaTurmas.setStyleSheet("background-color: white;\n"
"border: 1px solid #9FBBBF;\n"
"border-radius: 10px;\n"
"color: rgb(53, 62, 64);")
        self.listaTurmas.setObjectName("listaTurmas")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listaTurmas.addItem(item)
        self.stackedWidget.addWidget(self.pageTurmas)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-190, 0, 341, 821))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d3f9ff;\n"
"    border: 1px solid #a7c4a0;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #353e40;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #353e40;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover,  QPushButton:focus {\n"
"    background-color: #BEE0E6\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnAddProfessor = QtWidgets.QPushButton(self.frame_2)
        self.btnAddProfessor.setGeometry(QtCore.QRect(190, 80, 151, 51))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btnAddProfessor.setFont(font)
        self.btnAddProfessor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnAddProfessor.setTabletTracking(False)
        self.btnAddProfessor.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnAddProfessor.setAutoFillBackground(False)
        self.btnAddProfessor.setAutoDefault(False)
        self.btnAddProfessor.setStyleSheet("color: #353e40;"
        "border: none;"
        "background-color: #BEE0E6;"
        "")
        self.btnAddProfessor.setObjectName("btnAddProfessor")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btnAddProfessor)
        self.btnAddAluno = QtWidgets.QPushButton(self.frame_2)
        self.btnAddAluno.setGeometry(QtCore.QRect(190, 140, 151, 51))
        self.btnAddAluno.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnAddAluno.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnAddAluno.setObjectName("btnAddAluno")
        self.buttonGroup.addButton(self.btnAddAluno)
        self.btnVerAlunos = QtWidgets.QPushButton(self.frame_2)
        self.btnVerAlunos.setGeometry(QtCore.QRect(190, 200, 151, 51))
        self.btnVerAlunos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnVerAlunos.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnVerAlunos.setObjectName("btnVerAlunos")
        self.buttonGroup.addButton(self.btnVerAlunos)
        self.btnVerProfessores = QtWidgets.QPushButton(self.frame_2)
        self.btnVerProfessores.setGeometry(QtCore.QRect(190, 260, 151, 51))
        self.btnVerProfessores.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnVerProfessores.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnVerProfessores.setObjectName("btnVerProfessores")
        self.buttonGroup.addButton(self.btnVerProfessores)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(200, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btnVerTurmas = QtWidgets.QPushButton(self.frame_2)
        self.btnVerTurmas.setGeometry(QtCore.QRect(190, 320, 151, 51))
        self.btnVerTurmas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnVerTurmas.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnVerTurmas.setObjectName("btnVerTurmas")
        self.btnProximoBimestre = QtWidgets.QPushButton(self.frame_2)
        self.btnProximoBimestre.setGeometry(QtCore.QRect(190, 400, 151, 51))
        self.btnProximoBimestre.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnProximoBimestre.setText('Proximo Bimestre')
        self.btnProximoBimestre.setStyleSheet("QPushButton {\n"
"    background-color: #d3f9ff;\n"
"    border: 1px solid #9FBBBF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BEE0E6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9FBBBF;\n"
"}")
        self.buttonGroup.addButton(self.btnVerTurmas)
        self.btnLogout = QtWidgets.QPushButton(self.frame_2)
        self.btnLogout.setGeometry(QtCore.QRect(190, 760, 151, 61))
        self.btnLogout.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnLogout.setStyleSheet("QPushButton {\n"
"    background-color: #FFAE9F;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E69B8E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BF8177;\n"
"}")
        self.btnLogout.setObjectName("btnLogout")
        MainWindow.setCentralWidget(self.centralwidget)

        def mudar_cor(button):
                for btn in [self.btnAddAluno, self.btnAddProfessor, self.btnVerAlunos, self.btnVerProfessores, self.btnVerTurmas]:
                        btn.setStyleSheet("QPushButton {\n"
"    color: #353e40;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover,  QPushButton:focus {\n"
"    background-color: #BEE0E6\n"
"}\n")
                button.setStyleSheet('background-color: #BEE0E6')
                
        self.buttonGroup.buttonClicked.connect(mudar_cor)
        
        self.buttonGroup.setId(self.btnAddProfessor, 0)
        self.buttonGroup.setId(self.btnAddAluno, 1)
        self.buttonGroup.setId(self.btnVerAlunos, 2)
        self.buttonGroup.setId(self.btnVerProfessores, 3)
        self.buttonGroup.setId(self.btnVerTurmas, 4)

        def trocar_posicao_cursor(input):
            texto = input.text()
            #print(texto)
            if texto == '() -' or texto == '..-':
                input.setCursorPosition(0)

        self.telefoneProfessor.cursorPositionChanged.connect(lambda: trocar_posicao_cursor(self.telefoneProfessor))
        self.telefoneAluno.cursorPositionChanged.connect(lambda: trocar_posicao_cursor(self.telefoneAluno))

        self.cpfAluno.cursorPositionChanged.connect(lambda: trocar_posicao_cursor(self.cpfAluno))
        self.cpfProfessor.cursorPositionChanged.connect(lambda: trocar_posicao_cursor(self.cpfProfessor))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nomeProfessor, self.dataProfessor)
        MainWindow.setTabOrder(self.dataProfessor, self.cpfProfessor)
        MainWindow.setTabOrder(self.cpfProfessor, self.btnAdicionarAluno)
        MainWindow.setTabOrder(self.btnAdicionarAluno, self.emailProfessor)
        MainWindow.setTabOrder(self.emailProfessor, self.alunoNome)
        MainWindow.setTabOrder(self.alunoNome, self.responsavelAluno)
        MainWindow.setTabOrder(self.responsavelAluno, self.cpfAluno)
        MainWindow.setTabOrder(self.cpfAluno, self.btnAdicionarProfessor)
        MainWindow.setTabOrder(self.btnAdicionarProfessor, self.inputBuscarAlunos)
        MainWindow.setTabOrder(self.inputBuscarAlunos, self.btnBuscarAlunos)
        MainWindow.setTabOrder(self.btnBuscarAlunos, self.tabela_aluno)
        MainWindow.setTabOrder(self.tabela_aluno, self.btnEditarAlunos)
        MainWindow.setTabOrder(self.btnEditarAlunos, self.btnExcluirAlunos)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Painel do Admin"))
        self.label.setText(_translate("MainWindow", "Adicionar Professor"))
        self.label_8.setText(_translate("MainWindow", "Cpf:"))
        self.label_9.setText(_translate("MainWindow", "Nome:"))
        self.cpfProfessor.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.label_10.setText(_translate("MainWindow", "Data de nascimento:"))
        self.label_11.setText(_translate("MainWindow", "Email:"))
        self.btnAdicionarProfessor.setText(_translate("MainWindow", "Adicionar"))
        self.dataProfessor.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_17.setText(_translate("MainWindow", "Sexo:"))
        self.professorSexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.professorSexo.setItemText(1, _translate("MainWindow", "Feminino"))
        self.professorSexo.setItemText(2, _translate("MainWindow", "Indefinido"))
        self.telefoneProfessor.setInputMask(_translate("MainWindow", "(00) 00000-0000"))
        self.label_20.setText(_translate("MainWindow", "Telefone:"))
        self.label_2.setText(_translate("MainWindow", "Adicionar Aluno"))
        self.label_3.setText(_translate("MainWindow", "Nome:"))
        self.label_4.setText(_translate("MainWindow", "Data de nascimento:"))
        self.label_5.setText(_translate("MainWindow", "Cpf:"))
        self.label_7.setText(_translate("MainWindow", "Responsavel:"))
        self.cpfAluno.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.btnAdicionarAluno.setText(_translate("MainWindow", "Adicionar"))
        self.dataAluno.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_6.setText(_translate("MainWindow", "Email:"))
        self.alunoSexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.alunoSexo.setItemText(1, _translate("MainWindow", "Feminino"))
        self.alunoSexo.setItemText(2, _translate("MainWindow", "Indefinido"))
        self.label_18.setText(_translate("MainWindow", "Sexo:"))
        self.label_19.setText(_translate("MainWindow", "Telefone:"))
        self.telefoneAluno.setInputMask(_translate("MainWindow", "(00) 00000-0000"))
        self.label_13.setText(_translate("MainWindow", "Nome:"))
        self.btnBuscarAlunos.setText(_translate("MainWindow", "Buscar"))
        item = self.tabela_aluno.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabela_aluno.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabela_aluno.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tabela_aluno.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tabela_aluno.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tabela_aluno.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Responsavel"))
        item = self.tabela_aluno.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cpf"))
        item = self.tabela_aluno.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Matricula"))
        item = self.tabela_aluno.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tabela_aluno.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Telefone"))
        __sortingEnabled = self.tabela_aluno.isSortingEnabled()
        self.tabela_aluno.setSortingEnabled(False)
        self.tabela_aluno.setSortingEnabled(__sortingEnabled)
        self.btnEditarAlunos.setText(_translate("MainWindow", "Editar"))
        self.btnExcluirAlunos.setText(_translate("MainWindow", "Excluir"))
        self.label_14.setText(_translate("MainWindow", "Ver Alunos"))
        self.label_15.setText(_translate("MainWindow", "Ver Professores"))
        self.label_16.setText(_translate("MainWindow", "Nome:"))
        self.btnBuscarProfessor.setText(_translate("MainWindow", "Buscar"))
        self.btnEditarProfessor.setText(_translate("MainWindow", "Editar"))
        self.btnExcluirProfessor.setText(_translate("MainWindow", "Excluir"))
        item = self.tabela_professor.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabela_professor.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabela_professor.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tabela_professor.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tabela_professor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tabela_professor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cpf"))
        item = self.tabela_professor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tabela_professor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.tabela_professor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Matricula"))
        self.label_21.setText(_translate("MainWindow", "Turmas"))
        __sortingEnabled = self.listaTurmas.isSortingEnabled()
        self.listaTurmas.setSortingEnabled(False)
        item = self.listaTurmas.item(0)
        item.setText(_translate("MainWindow", "Fundamental"))
        item = self.listaTurmas.item(1)
        item.setText(_translate("MainWindow", "1º Ano"))
        item = self.listaTurmas.item(2)
        item.setText(_translate("MainWindow", "2º Ano"))
        item = self.listaTurmas.item(3)
        item.setText(_translate("MainWindow", "3º Ano"))
        item = self.listaTurmas.item(4)
        item.setText(_translate("MainWindow", "4º Ano"))
        item = self.listaTurmas.item(5)
        item.setText(_translate("MainWindow", "5º Ano"))
        item = self.listaTurmas.item(6)
        item.setText(_translate("MainWindow", "6º Ano"))
        item = self.listaTurmas.item(7)
        item.setText(_translate("MainWindow", "7º Ano"))
        item = self.listaTurmas.item(8)
        item.setText(_translate("MainWindow", "8º Ano"))
        item = self.listaTurmas.item(9)
        item.setText(_translate("MainWindow", "9º Ano"))
        item = self.listaTurmas.item(10)
        item.setText(_translate("MainWindow", "Medio"))
        item = self.listaTurmas.item(11)
        item.setText(_translate("MainWindow", "1º Ano"))
        item = self.listaTurmas.item(12)
        item.setText(_translate("MainWindow", "2º Ano"))
        item = self.listaTurmas.item(13)
        item.setText(_translate("MainWindow", "3º Ano"))
        
        self.listaTurmas.setSortingEnabled(__sortingEnabled)
        self.btnAddProfessor.setText(_translate("MainWindow", "Adicionar Professor"))
        self.btnAddAluno.setText(_translate("MainWindow", "Adicionar Aluno"))
        self.btnVerAlunos.setText(_translate("MainWindow", "Ver Alunos"))
        self.btnVerProfessores.setText(_translate("MainWindow", "Ver Professores"))
        self.label_12.setText(_translate("MainWindow", "Escola"))
        self.btnVerTurmas.setText(_translate("MainWindow", "Turmas"))
        self.btnLogout.setText(_translate("MainWindow", "Logout"))
